name: Build site and publish to GitHub Pages

on:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: "Build site and deploy"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Ruby and install bundle packages
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.1"
        bundler-cache: true
        cache-version: 0 # Increment this number if you need to re-download cached gems

    - name: Override site.url
      run: sed 's;URL;https://wks.github.io;' < _config.url_override.template.yml > _config.url_override.yml
        
    - name: Build with Jekyll
      run: bundle exec jekyll build --config _config.yml,_config.url_override.yml
      env:
        JEKYLL_ENV: production

    - name: List files in _site for debugging
      run: find ./_site

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.GHPAGE_DEPLOY_KEY }}
        external_repository: wks/wks.github.io
        publish_branch: master
        publish_dir: ./_site

