name: Build site and publish to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    name: "Build site and deploy"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install bundle packages
      run: bundle install
        
    - name: Build with Jekyll
      run: bundle exec jekyll build

    - name: Debug
      run: find .

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.GHPAGE_DEPLOY_KEY }}
        external_repository: wks/wks.github.io
        publish_branch: master
        publish_dir: ./_site

